spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: "${POSTGRES_JDBC}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver

springdoc:
  show-actuator: true

application:
  external-url: "${EXTERNAL_URL}"
  offer-validity: 2592000
