spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: "jdbc:postgresql://localhost:5434/issuer_db"
    username: "oid4vc_user"
    password: "secret"
    driver-class-name: org.postgresql.Driver

springdoc:
  show-actuator: true

application:
  external-url: "http://localhost:8080/"
  offer-validity: 2592000 # 60 * 60 * 24 * 30 => 30 days;
controller:
  # Use DEV Environment
  uri: "https://status-data-service-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch"