spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: "jdbc:postgresql://localhost:5434/issuer_db"
    username: "oid4vc_user"
    password: "secret"
    driver-class-name: org.postgresql.Driver

springdoc:
  show-actuator: true

application:
  external-url: "http://localhost:8080/"