spring:
  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          # https://stackoverflow.com/questions/10075081/hibernate-slow-to-acquire-postgres-connection
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    locations: classpath:db/migration/common
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: "${POSTGRES_JDBC}"
    username: "${secret.db.username:${POSTGRES_USER}}"
    password: "${secret.db.password:${POSTGRES_PASSWORD}}"
  data:
    jpa:
      repositories:
        # Avoid hangs on startup, see https://github.com/spring-projects/spring-framework/issues/25111
        bootstrap_mode: default

springdoc:
  show-actuator: true

application:
  # DID of the Issuer
  issuer-id: ${ISSUER_ID}
  # URL under which this service can be reached from the web
  external-url: ${EXTERNAL_URL}
  offer-validity: 2592000
  enable-jwt-authentication: ${ENABLE_JWT_AUTH:false}
  authentication-jwks: ${JWKS_ALLOWLIST}
  status-list:
    # URL where this service shall write status list updates to
    controller-url: "${CONTROLLER_URL}"
    # private key for singing status list VCs
    private-key: "${secret.key.status-list.key:${STATUS_LIST_KEY}}"
    # value to be added to the kid of the created status list; should be available in the published did document.
    verification-method: "${DID_STATUS_LIST_VERIFICATION_METHOD}"
logging:
  level:
    ch.admin.bit.eid.issuer_management.infrastructure.logging.RequestLoggingFilter: DEBUG