spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: "jdbc:postgresql://localhost:5434/issuer_db"
    username: "oid4vc_user"
    password: "secret"
    driver-class-name: org.postgresql.Driver

springdoc:
  show-actuator: true

application:
  external-url: "http://localhost:8080/"
  offer-validity: 2592000 # 60 * 60 * 24 * 30 => 30 days;
  status-list:
    private-key: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIDqMm9PvL4vpyFboAwaeViQsH30CkaDcVtRniZPezFxpoAoGCCqGSM49\nAwEHoUQDQgAEQgjeqGSdu+2jq8+n78+6fXk2Yh22lQKBYCnu5FWPvKtat3wFEsQX\nqNHYgPXBxWmOBw5l2PE/gUDUJqGJSc1LuQ==\n-----END EC PRIVATE KEY-----"
    controller-url: "https://status-authoring-service-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/"

logging:
  level:
    hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN